# 程序运行端口
listen-port = ":9527"

[db]
host = "172.16.4.215"
port = 5000
user = "root"
password = ""
db-name = "dmgr"


[log]
# 日志 level
log-level = "info"
# 日志文件路径
log-file = "./dmgr.log"
# 每个日志文件保存的最大尺寸 单位：M
max-size = 128
# 文件最多保存多少天
max-age = 7
# 日志文件最多保存多少个备份
max-backups = 30


[middleware]
# rateLimiter 最大访问速率
max-rate-limiter = 30
# jwt 中间件设置
# jwt标识
jwt-realm = "marvin"
# 服务端密钥
jwt-key = "pingcap"
# token过期时间（h）
jwt-timeout = 24
# token更新时间（h）
jwt-max-refresh = 24